# Generated by Django 5.2.5 on 2025-10-29 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biosketch', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('researchgate_link', models.URLField(blank=True, null=True)),
                ('pubmed_link', models.URLField(blank=True, null=True)),
                ('google_scholar_link', models.URLField(blank=True, null=True)),
                ('x_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phd_details', models.TextField(blank=True, null=True)),
                ('masters_details', models.TextField(blank=True, null=True)),
                ('graduation_details', models.TextField(blank=True, null=True)),
                ('school_details', models.TextField(blank=True, null=True)),
                ('articles_journals', models.TextField(blank=True, null=True)),
                ('book_chapters', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_experience', models.TextField(blank=True, null=True)),
                ('past_experiences', models.TextField(blank=True, null=True)),
                ('skill_set', models.TextField(blank=True, null=True)),
                ('languages_spoken', models.CharField(blank=True, max_length=255, null=True)),
                ('certifications', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
