# Generated by Django 5.2.5 on 2025-11-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_personaldetail_professionaldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='profile_image',
        ),
    ]
