# Generated by Django 5.2.5 on 2025-11-14 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_comment_comment_c_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='graduation_details',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='masters_details',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='phd_details',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='school_details',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('end_date', models.DateField()),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_list', to='accounts.personaldetail')),
            ],
        ),
    ]
