# Generated by Django 5.2.5 on 2025-11-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_education_personal_detail_education_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
