# Generated by Django 5.2.5 on 2025-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_education_course_name_alter_education_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('speaker', 'Speaker')], default='user', max_length=20),
        ),
    ]
