# Generated by Django 5.2.5 on 2025-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_folder_folderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderitem',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
