# Generated by Django 5.2.5 on 2025-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_folderitem_file_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folderitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='folderitem',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='folderitem',
            name='file',
        ),
        migrations.RemoveField(
            model_name='folderitem',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='folderitem',
            name='file_type',
        ),
        migrations.AddField(
            model_name='folderitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folderitem',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
