# Generated by Django 5.2.5 on 2025-12-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_folderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
