# Generated by Django 5.2.5 on 2025-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_calendarevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='end_datetime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='start_datetime',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='remind_before',
            field=models.IntegerField(default=10),
        ),
    ]
