# Generated by Django 5.2.5 on 2025-12-23 10:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_end_datetime_calendarevent_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-start_year']},
        ),
        migrations.RenameField(
            model_name='personaldetail',
            old_name='google_scholar_link',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='professionaldetail',
            old_name='current_experience',
            new_name='current_description',
        ),
        migrations.RenameField(
            model_name='professionaldetail',
            old_name='past_experiences',
            new_name='work_address',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='pubmed_link',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='researchgate_link',
        ),
        migrations.AddField(
            model_name='education',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='lab_or_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='education',
            name='place',
            field=models.CharField(blank=True, help_text='City / State', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='research_interests',
            field=models.JSONField(blank=True, help_text='List of research interests (only for PhD/PostDoc)', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='research_summary',
            field=models.TextField(blank=True, help_text='Brief discussion of research work', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='topic',
            field=models.CharField(blank=True, help_text='Thesis / Research topic', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='research_links',
            field=models.JSONField(blank=True, help_text='List of links like ResearchGate, PubMed, Google Scholar, NCBI', null=True),
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='current_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='current_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='current_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='current_start_month',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True),
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='current_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='lab',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='course_name',
            field=models.CharField(help_text='Course / Program name (e.g. Biotechnology, AI)', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('postdoc', 'Postdoctoral'), ('diploma', 'Diploma'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='x_handle',
            field=models.CharField(blank=True, help_text='Twitter/X username without URL', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PastExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('start_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('start_year', models.IntegerField()),
                ('end_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('end_year', models.IntegerField()),
                ('description', models.TextField(blank=True, help_text='Brief description of work done', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_year', '-end_month'],
            },
        ),
    ]
