# Generated by Django 5.2.5 on 2025-12-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
