# Generated by Django 5.2.5 on 2025-12-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_education_degree_alter_personaldetail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
