# Generated by Django 5.2.5 on 2026-01-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_education_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_preview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
