# Generated by Django 5.2.5 on 2026-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_post_link_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has done payment or not.', verbose_name='verified status'),
        ),
    ]
