# Generated by Django 5.2.5 on 2026-01-09 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldetail',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ScientificInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_area_of_expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('major_focus', models.JSONField(blank=True, help_text='List of major research focus areas', null=True)),
                ('specific_research_areas', models.JSONField(blank=True, help_text='List of specific research areas', null=True)),
                ('organ_sites', models.JSONField(blank=True, help_text='List of organ sites', null=True)),
                ('additional_research_areas', models.JSONField(blank=True, help_text='Additional research expertise areas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_interest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
