# Generated by Django 5.2.5 on 2026-01-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_professionaldetail_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificinterest',
            name='brief_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
