# Generated by Django 5.2.5 on 2026-02-05 10:02

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_lite',
            field=models.BooleanField(default=False, verbose_name='verified status lite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
