# Generated by Django 5.2.5 on 2026-02-10 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_is_verified_lite_alter_user_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/featured/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/')),
                ('specialization', models.CharField(help_text='Eg: Neuroscience, AI, Biology', max_length=255)),
                ('abstract', models.TextField()),
                ('acknowledgements', models.TextField(blank=True, null=True)),
                ('author_contributions', models.TextField(blank=True, null=True)),
                ('funding', models.TextField(blank=True, null=True)),
                ('competing_interests', models.TextField(blank=True, null=True)),
                ('disclosures_ethics', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('introduction', 'Introduction'), ('materials_methods', 'Materials & Methods'), ('results', 'Results'), ('discussion', 'Discussion'), ('conclusion', 'Conclusion'), ('custom', 'Custom')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/figures/')),
                ('caption', models.TextField(blank=True)),
                ('figure_number', models.PositiveIntegerField(editable=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='accounts.article')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='accounts.articlesection')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleKeywordMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_maps', to='accounts.article')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.articlekeyword')),
            ],
            options={
                'unique_together': {('article', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'rating'], name='accounts_ar_article_6da42c_idx')],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ArticleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='accounts.article')),
                ('referenced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_mentions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'user'], name='accounts_ar_article_71518e_idx')],
                'unique_together': {('article', 'user')},
            },
        ),
    ]
