# Generated by Django 5.2.5 on 2026-02-16 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_articlekeyword_article_articlesection_articlefigure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.event'),
        ),
        migrations.AlterField(
            model_name='program',
            name='speaker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'speaker'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
