# Generated by Django 5.2.5 on 2026-02-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_program_event_alter_program_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_lite',
            field=models.BooleanField(default=True, verbose_name='verified status lite'),
        ),
    ]
