# Generated by Django 5.2.5 on 2026-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_is_verified_lite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_lite',
            field=models.BooleanField(default=False, verbose_name='verified status lite'),
        ),
    ]
