# Generated by Django 5.2.5 on 2026-03-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_registration_paymentattempt_manualpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategoryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='accounts.event')),
            ],
            options={
                'unique_together': {('event', 'category')},
            },
        ),
    ]
