# Generated by Django 5.2.5 on 2026-03-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_eventcategorypricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='pricing',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='accounts.eventcategorypricing'),
            preserve_default=False,
        ),
    ]
