# Generated by Django 5.2.5 on 2026-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_registration_event_registration_pricing'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('email', 'event'), name='unique_user_event_registration'),
        ),
    ]
