# Generated by Django 5.2.5 on 2026-04-01 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_registration_unique_user_event_registration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_user_event_registration',
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='CREATED', max_length=20),
        ),
    ]
