# Generated by Django 4.2.30 on 2026-04-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0046_remove_registration_unique_user_event_registration_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_posts",
                to="accounts.article",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="articlefigure",
            name="image",
            field=models.CharField(max_length=500),
        ),
    ]
